# Generated by Django 5.0.3 on 2024-06-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userbudget_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinearIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("api_key", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SlackIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("bot_token", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="pilotuser",
            name="linear_integration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.linearintegration",
            ),
        ),
        migrations.AddField(
            model_name="pilotuser",
            name="slack_integration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.slackintegration",
            ),
        ),
    ]
