# Generated by Django 5.0.3 on 2024-06-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_linearintegration_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linearintegration",
            name="api_key",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="slackintegration",
            name="bot_token",
            field=models.TextField(null=True),
        ),
    ]
