# Generated by Django 5.0.3 on 2024-06-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_linearintegration_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackintegration",
            name="user_token",
            field=models.TextField(null=True),
        ),
    ]
