# Generated by Django 5.0.3 on 2024-06-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_slackintegration_user_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="linearintegration",
            old_name="api_key",
            new_name="access_token",
        ),
    ]
