# Generated by Django 5.0.3 on 2024-06-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_sentryintegration_pilotuser_sentry_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentryintegration",
            name="org_id_or_slug",
            field=models.TextField(null=True),
        ),
    ]
