# Generated by Django 5.0.3 on 2024-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0014_task_gpt_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.BinaryField(
                blank=True, help_text="An image to be used in the task", null=True
            ),
        ),
    ]
