# Generated by Django 5.0.3 on 2024-06-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0015_task_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="comment_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
