# Generated by Django 5.0.3 on 2024-06-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0016_alter_task_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="installation_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="response_comment_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
